var fs = require('fs')
var path = require('path')

var replace = {
  'CENTRAL COAST':'Central Coast',
  'CENTRAL WEST & ORANA':'Central West and Orana',
  'FAR WEST':'Far West',
  'HUNTER':'Hunter',
  'ILLAWARRA':'Illawarra-Shoalhaven',
  'METROPOLITAN SYDNEY':'Metropolitan Sydney',
  'MURRAY-MURRUMBIDGEE':'New England North West',
  'NEW ENGLAND - NORTH WEST':'North Coast',
  'NORTH COAST':'Riverina-Murray',
  'SOUTH EAST & TABLELANDS':'South East and Tablelands',





  'ALBURY':'Albury',
  'ARMIDALE REGIONAL':'Armidale Regional',
  'BALLINA':'Ballina',
  'BALRANALD':'Balranald',
  'BATHURST REGIONAL':'Bathurst',
  'BEGA VALLEY':'Bega Valley',
  'BELLINGEN':'Bellingen',
  'BERRIGAN':'Berrigan',
  'BLACKTOWN':'Blacktown',
  'BLAND':'Bland',
  'BLAYNEY':'Blayney',
  'BLUE MOUNTAINS':'Blue Mountains',
  'BOGAN':'Bogan',
  'BOTANY BAY':'Botany Bay',
  'BOURKE':'Bourke',
  'BREWARRINA':'Brewarrina',
  'BROKEN HILL':'Broken Hill',
  'BURWOOD':'Burwood',
  'BYRON':'Byron',
  'CABONNE':'Cabonne',
  'CAMDEN':'Camden',
  'CAMPBELLTOWN':'Campbelltown',
  'CANADA BAY':'Canada Bay',
  'CANTERBURY-BANKSTOWN':'Canterbury-Bankstown',
  'CARRATHOOL':'Carrathool',
  'CENTRAL COAST':'Central Coast',
  'CENTRAL DARLING':'Central Darling',
  'CESSNOCK':'Cessnock',
  'CLARENCE VALLEY':'Clarence Valley',
  'COBAR':'Cobar',
  'COFFS HARBOUR':'Coffs Harbour',
  'COOLAMON':'Coolamon',
  'COONAMBLE':'Coonamble',
  'COWRA':'Cowra',
  'CUMBERLAND':'Cumberland',
  'DUNGOG':'Dungog',
  'EDWARD RIVER':'Edward River',
  'EUROBODALLA':'Eurobodalla',
  'FAIRFIELD':'Fairfield',
  'FEDERATION':'Federation',
  'FORBES':'Forbes',
  'GEORGES RIVER':'Georges River',
  'GILGANDRA':'Gilgandra',
  'GLEN INNES SEVERN':'Glen Innes Severn',
  'GOULBURN MULWAREE':'Goulburn Mulwaree',
  'GREATER HUME':'Greater Hume',
  'GRIFFITH':'Griffith',
  'GUNDAGAI':'Gundagai',
  'GUNNEDAH':'Gunnedah',
  'GWYDIR':'Gwydir',
  'HAWKESBURY':'Hawkesbury',
  'HAY':'Hay',
  'HILLTOPS':'Hilltops',
  'HORNSBY':'Hornsby',
  'HUNTERS HILL':'Hunters Hill',
  'INNER WEST':'Inner West',
  'INVERELL':'Inverell',
  'JUNEE':'Junee',
  'KEMPSEY':'Kempsey',
  'KIAMA':'Kiama',
  'KU-RING-GAI':'Ku-ring-gai',
  'KYOGLE':'Kyogle',
  'LACHLAN':'Lachlan',
  'LAKE MACQUARIE':'Lake Macquarie',
  'LANE COVE':'Lane Cove',
  'LEETON':'Leeton',
  'lga':'Lga',
  'LISMORE':'Lismore',
  'LITHGOW':'Lithgow',
  'LIVERPOOL':'Liverpool',
  'LIVERPOOL PLAINS':'Liverpool Plains',
  'LOCKHART':'Lockhart',
  'MAITLAND':'Maitland',
  'MID-COAST':'Mid-coast',
  'MID-WESTERN REGIONAL':'Mid-Western',
  'MOREE PLAINS':'Moree Plains',
  'MOSMAN':'Mosman',
  'MURRAY RIVER':'Murray River',
  'MURRUMBIDGEE':'Murrumbidgee',
  'MUSWELLBROOK':'Muswellbrook',
  'NAMBUCCA':'Nambucca',
  'NARRABRI':'Narrabri',
  'NARRANDERA':'Narrandera',
  'NARROMINE':'Narromine',
  'NEWCASTLE':'Newcastle',
  'NORTH SYDNEY':'North Sydney',
  'NORTHERN BEACHES':'Northern Beaches',
  'OBERON':'Oberon',
  'ORANGE':'Orange',
  'PARKES':'Parkes',
  'PARRAMATTA':'City of Parramatta',
  'PENRITH':'Penrith',
  'PORT MACQUARIE-HASTINGS':'Port Macquarie-Hastings',
  'PORT STEPHENS':'Port Stephens',
  'QUEANBEYAN-PALERANG REGIONAL':'Queanbeyan-Palerang Regional',
  'RANDWICK':'Randwick',
  'RICHMOND VALLEY':'Richmond Valley',
  'ROCKDALE':'Rockdale',
  'RYDE':'Ryde',
  'SHELLHARBOUR':'Shellharbour',
  'SHOALHAVEN':'Shoalhaven',
  'SINGLETON':'Singleton',
  'SNOWY MONARO REGIONAL':'Snowy Monaro Regional',
  'SNOWY VALLEYS':'Snowy Valleys',
  'STRATHFIELD':'Strathfield',
  'SUTHERLAND':'Sutherland',
  'SYDNEY':'Sydney',
  'TAMWORTH REGIONAL':'Tamworth',
  'TEMORA':'Temora',
  'TENTERFIELD':'Tenterfield',
  'THE HILLS':'The Hills',
  'TWEED':'Tweed',
  'UNINCORPORATED':'Unincorporated Far West',
  'UPPER HUNTER':'Upper Hunter',
  'UPPER LACHLAN':'Upper Lachlan',
  'URALLA':'Uralla',
  'WAGGA WAGGA':'Wagga Wagga',
  'WALCHA':'Walcha',
  'WALGETT':'Walgett',
  'WARREN':'Warren',
  'WARRUMBUNGLE':'Warrumbungle',
  'WAVERLEY':'Waverley',
  'WEDDIN':'Weddin',
  'WENTWORTH':'Wentworth',
  'WESTERN PLAINS REGIONAL':'Western Plains Regional',
  'WILLOUGHBY':'Willoughby',
  'WINGECARRIBEE':'Wingecarribee',
  'WOLLONDILLY':'Wollondilly',
  'WOLLONGONG':'Wollongong',
  'WOOLLAHRA':'Woollahra',
  'YASS VALLEY':'Yass Valley',
}

fs.readFile(path.join(__dirname, 'mapping.csv'), 'utf-8', function(err, data){
  var d = data
  for (var a in replace){
    var b = replace[a]
    d = d.split(a).join(b)
  }
  fs.writeFile(path.join(__dirname,'mapping_fix.csv'), d)
})
